repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.9-for-vscode
    hooks:
      - id: prettier
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        name: black
        description: Code formatting
        language_version: python3
  - repo: https://github.com/pycqa/flake8
    rev: "6.0.0"
    hooks:
      - id: flake8
        name: flake8
        description: linting and code style
        args: [--config=.flake8]
        additional_dependencies:
          [
            flake8-builtins,
            flake8-docstrings,
            flake8-bandit,
            flake8-pytest-style,
            flake8-cognitive-complexity,
            flake8-expression-complexity,
          ]
  - repo: https://github.com/terrencepreilly/darglint
    rev: "v1.8.1"
    hooks:
      - id: darglint
        name: darglint
        description: Docstring linting
        exclude: ^(tests/|noxfile.py)
